openapi: 3.1.0
info:
  title: payments
  version: '1.0'
  contact:
    name: Settle Group
    url: 'https://settle.eu'
    email: hello@settle.eu
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/SettleAPI/settle-api-description/main/LICENSE'
  description: |
    This is an experimental feature, aimed towards larger enterprises and therefore only accessible as part of the Settle API, with the following requirements/limitations:
    - Approval: The business needs to be approved for a pre-paid M2P account (merchant-to-person) balance, which the service then consumes until empty.
    - No cross-border: receiver MSISDN needs to be in the same jurisdiction as the business.
    - No foreign exchange: only local currency of the business allowed.

    It is recommended that you start out with testing this feature in the Settle Sandbox 
  summary: Settle Send allows Settle businesses to send any amount within the current limits funded by means of topping up a dedicated Settle Send stored value account.
servers:
  - url: 'http://localhost:3000'
    description: Mock
  - url: 'https://api.sandbox.settle.eu/payment/v2'
    description: Sandbox
  - url: 'https://api.settle.eu/payments/v2'
    description: Production
paths:
  /payment:
    post:
      summary: payment.send
      operationId: payment.send
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Insufficient funds:
                  value:
                    error_detail: null
                    error_type: Bad Request
                    error_description: Insufficient funds
          headers: {}
        '401':
          description: Unauthorized
      description: Send payment
      requestBody:
        $ref: '#/components/requestBodies/payment.send'
      tags:
        - Payment
    parameters: []
  '/payment/{tid}':
    parameters:
      - $ref: ./merchant.v1.yaml#/components/parameters/tid
    get:
      summary: payment.send.outcome
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    object:
                      idempotency_id: 63de8b62-dac3-4ec1-8da3-1093e561583a
                      payer: 5rg1dkk8
                      currency: NOK
                      timestamp: '2021-06-22 09:14:26'
                      require_identified: false
                      id: p13fjg6py9jw
                      payee: 'msisdn:4798052301'
                      amount: 1000
                      payer_status: ok
                      chat_text: Cumque illo ut est ex unde.
                    type: payment
                properties:
                  object:
                    type: object
                    properties:
                      idempotency_id:
                        type: string
                        minLength: 1
                      payer:
                        $ref: ../models/PersonIdentifier.v1.yaml
                      currency:
                        $ref: ../models/Currency.v1.yaml
                      timestamp:
                        type: string
                        minLength: 1
                      require_identified:
                        type: boolean
                      id:
                        type: string
                        minLength: 1
                      payee:
                        type: string
                        minLength: 1
                      amount:
                        $ref: ../models/MoneyInteger.v1.yaml
                      payer_status:
                        type: string
                        minLength: 1
                      chat_text:
                        type: string
                        minLength: 1
                  type:
                    type: string
                    minLength: 1
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error_detail:
                    type: object
                    properties: {}
                    required: []
                  error_type:
                    type: string
                    minLength: 1
                  error_description:
                    type: string
                    minLength: 1
                required:
                  - error_detail
                  - error_type
                  - error_description
                x-examples:
                  example-1:
                    error_detail: {}
                    error_type: Not Found
                    error_description: no payment request with id p0gv8xc9d3km
              examples:
                No payment found:
                  value:
                    error_detail: {}
                    error_type: Not Found
                    error_description: no payment request with ID xxx
      operationId: payment.send.outcome
      description: Get Payment details
components:
  schemas: {}
  requestBodies:
    payment.send:
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                payer:
                  type: string
                  description: The merchant ID of the sender
                payee:
                  $ref: ../models/PersonIdentifier.v1.yaml
                idempotency_id:
                  type: string
                  description: Unique id for each payment request.
                currency:
                  $ref: ../models/Currency.v1.yaml
                amount:
                  $ref: ../models/MoneyInteger.v1.yaml
                chat_text:
                  type: string
                  description: Message presented to the user with the payment.
                expires_in:
                  type: string
                  description: 'Number of seconds the funds can not be claimed immediately, how long will they be available before being returned to the sender. Default is three (3) days.'
                required_identified:
                  type: boolean
                  default: false
                  description: Option to request the recipient to have a verified identity in order to receive the funds.
            properties:
              payer:
                type: string
                description: The merchant ID of the sender.
              payee:
                $ref: ../models/PersonIdentifier.v1.yaml
              idempotency_id:
                type: string
                description: Unique id for each payment request.
              currency:
                $ref: ../models/Currency.v1.yaml
              amount:
                $ref: ../models/MoneyInteger.v1.yaml
              chat_text:
                type: string
                description: Message presented to the user with the payment.
              expires_in:
                type: string
                description: 'Number of seconds the funds can not be claimed immediately, how long will they be available before being returned to the sender. Default is three (3) days.'
              required_identified:
                type: boolean
                description: Option to request the recipient to have a verified identity in order to receive the funds.
                default: false
            required:
              - payer
              - payee
              - idempotency_id
              - currency
              - amount
      description: 'Send payment. **Please note** that using the same `idempotency_id` again in a new request will only result in the retrieval of the first resulting Transaction ID (`tid`), not a new payment, mnng it is safe to retry payment requests in case of network loss.'
tags:
  - name: Payment
