openapi: 3.1.0
info:
  title: Short Dynamic Links API
  version: '1.0'
  description: |
    You can use the Short Dynamic Links REST API to generate Short Dynamic Links from ShortLinks. See the [ShortLinks and Short Dynamic Links article](./ZG9jOjM0ODE0NTkz-short-links) article to get started.

    ## HTTP Request

    ```Http
    POST https://dynamiclinks.settle.dev/api/create
    ```

    #

    ## Request Body

    ```json title="Specify the Dynamic Link parameters as a JSON object"
    {
      "shortLink": "https://settle.eu/s/gSpEb/pos123/",
      "environment": "production"
    }
    ```

    ### Request Parameters

    All parameters are optional unless otherwise specified.

    #### General parameters

    ```json json_schema
    {
      "title": "Request Body",
      "type": "object",
      "properties": {
        "shortLink": {
          "type": "string",
          "description": "Settle [ShortLink](./ZG9jOjM0ODE0NTkz-short-links)."
        },
        "environment": {
          "type": "string",
          "description": "The environment where you want to create the Short Dynamic Link.",
          "enum": ["sandbox", "production"]
        }
      },
      "required": ["shortLink", "environment"]
    }
    ```

    #### Social Meta Tag parameters

    ```json json_schema
    {
      "title": "Request Body",
      "type": "object",
      "properties": {
        "socialTitle": {
          "type": "string",
          "description": "The title to use when the Dynamic Link is shared in a social post."
        },
        "socialDescription": {
          "type": "string",
          "description": "The description to use when the Dynamic Link is shared in a social post.",
        },
        "socialImageLink": {
          "type": "string",
          "description": "The URL to an image related to this link.",
        }
      },
    }
    ```

    ## Response Body

    ```json title="The response to a request is a JSON object"
    {
      "shortDynamicLink": "https://get.settle.eu/Vv3H",
      "previewDynamicLink": "https://get.settle.eu/Vv3H?d=1"
    }
    ```

    ### Response Paramaters

    ```json json_schema
    {
      "title": "Response Body",
      "type": "object",
      "properties": {
        "shortDynamicLink": {
          "type": "string",
          "description": "The generated Dynamic Link."
        },
        "previewDynamicLink": {
          "type": "string",
          "description": "A link to a flowchart of the Dynamic Link's behavior.",
        }
      },
    }
    ```
  summary: 'You can use the Short Dynamic Links REST API to generate Short Dynamic Links from ShortLinks. See the [ShortLinks and Short Dynamic Links article](./ZG9jOjM0ODE0NTkz-short-links) article to get started.'
  contact:
    name: Settle Group
    url: 'https://www.settle.eu/developer'
    email: support+dev@settle.eu
  license:
    identifier: MIT
    name: MIT
servers:
  - url: 'https://dynamiclinks.settle.dev/api/'
paths:
  /create:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '201':
          $ref: '#/components/responses/create'
      operationId: get-create
      description: Create new Short Dynamic Link
      requestBody:
        $ref: '#/components/requestBodies/create'
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  requestBodies:
    create:
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                shortLink: 'https://settle.eu/s/gSpEb/pos123/'
                environment: production
            properties:
              shortLink:
                type: string
                minLength: 1
                description: 'Settle [ShortLink](./ZG9jOjM0ODE0NTkz-short-links).'
              environment:
                type: string
                minLength: 1
                description: The environment where you want to create the Short Dynamic Link.
                enum:
                  - sandbox
                  - production
              socialTitle:
                type: string
                description: The title to use when the Dynamic Link is shared in a social post.
              socialDescription:
                type: string
                description: The description to use when the Dynamic Link is shared in a social post.
              socialImageLink:
                type: string
                description: The URL to an image related to this link.
            required:
              - shortLink
              - environment
      description: All parameters are optional unless otherwise specified.
  responses:
    create:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                shortDynamicLink: 'https://get.settle.eu/Vv3H'
                previewDynamicLink: 'https://get.settle.eu/Vv3H?d=1'
            properties:
              shortDynamicLink:
                type: string
                minLength: 1
                description: The generated Dynamic Link.
              previewDynamicLink:
                type: string
                minLength: 1
                description: A link to a flowchart of the Dynamic Link's behavior.
