openapi: 3.0.0
info:
  title: users
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /permission_request:
    post:
      summary: users.permissions.request.create
      operationId: users.permissions.request.create
      responses:
        '200':
          description: 'OK, identical permission request already created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Permission Request ID
                    default: 'null'
        '201':
          description: Permission request created
        '400':
          description: 'Bad request, validation error'
      description: |-
        Create permission request.

        The call is idempotent; that is, if one posts the same pos_id and pos_tid twice, only one Permission request is created.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/permissions.request.create'
  '/permission_request/{rid}':
    parameters:
      - $ref: '#/components/parameters/rid'
    get:
      summary: users.permissions.request.get
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/permissions.request.get.200'
      operationId: users.permissions.request.get
      description: See permission request info
components:
  schemas:
    permissions.request.create:
      title: 'Request Body: permissions.request.create'
      type: object
      description: Create Permission Request
      properties:
        customer:
          $ref: ../models/PersonIdentifier.v1.yaml
        pos_id:
          type: string
          description: 'The POS this permission request originates from, used for informing user about origin.'
          maxLength: 64
          pattern: '^[a-zA-Z0-9_.-]+$'
        pos_tid:
          type: string
          description: Local transaction id for POS. This must be unique for the POS.
          pattern: '^[a-zA-Z0-9_.-]+$'
          maxLength: 64
        text:
          type: string
          description: Local transaction id for POS. This must be unique for the POS.
          default: 'null'
        callback_uri:
          type: string
          description: 'If provided, Settle will POST to this URI when the status of the permission request changes. The data transferred in the POST are the same as what can be retrieved by calling GET on the resource URI.'
          default: 'null'
        scope:
          type: string
          description: 'Space-delimited list of scopes. Any of: "openid" (static id, "address" (user preferred address), "profile" (name), "phone", "email", "shipping_address", "fodselsnummer".'
        expires_in:
          type: string
          description: Expiration in seconds from when server received request.
          default: '21600'
          maxLength: 2592000
      required:
        - customer
        - pos_id
        - pos_tid
        - scope
      x-examples: {}
  parameters:
    rid:
      name: rid
      in: path
      required: true
      schema:
        type: string
      description: Permission request id assigned by Settle
  responses:
    permissions.request.get.200:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                customer: 'null'
                pos_id: string
                pos_tid: string
                text: 'null'
                callback_uri: 'null'
                scope: string
                expires_in: '21600'
            properties:
              customer:
                $ref: ../models/PersonIdentifier.v1.yaml
              pos_id:
                type: string
                minLength: 1
                pattern: '^[a-zA-Z0-9_.-]+$'
                maxLength: 64
                description: 'The POS this permission request originates from, used for informing user about origin.'
              pos_tid:
                type: string
                minLength: 1
                pattern: '^[a-zA-Z0-9_.-]+$'
                maxLength: 64
                description: Local transaction id for POS. This must be unique for the POS.
              text:
                type: string
                description: Text that is shown to user when asked for permission. This can contain linebreaks and the text has to fit on smartphones screens.
                default: 'null'
              callback_uri:
                type: string
                description: 'If provided, Settle will POST to this URI when the status of the permission request changes. The data transferred in the POST are the same as what can be retrieved by calling GET on the resource URI.'
                default: 'null'
              scope:
                type: string
                description: 'Space-delimited list of scopes. Any of: "openid" (static id, "address" (user preferred address), "profile" (name), "phone", "email", "shipping_address", "fodselsnummer".'
                default: 'null'
              expires_in:
                $ref: ../models/DateTime.yaml
            required:
              - customer
              - pos_id
              - pos_tid
              - scope
      headers: {}
